-- 평문으로 이관된 tb_managerinfo.manager_password를 EgovFileScrty(SHA-256+salt=managerId) 해시로 재암호화
-- ⚠️ 반드시 한 번만 실행할 것 (재실행하면 이미 해시된 값을 다시 해시해서 로그인이 깨짐)
BEGIN;

UPDATE tb_managerinfo SET manager_password = 'Ec6oQ68VYB+ZNAxmZc1C7QeIzpDqxG/Ov3EVTc2eM3A=' WHERE manager_id = 'truser';
UPDATE tb_managerinfo SET manager_password = 'n42GLs8F9UXn15krFoQZr4OCHGbYm+ECSKtk9FjJRdk=' WHERE manager_id = 'msTest';
UPDATE tb_managerinfo SET manager_password = 'INO86Hhqeotkby2fHpRf3alHfYprFBkdQtTuHGBK0Uc=' WHERE manager_id = '193523';
UPDATE tb_managerinfo SET manager_password = 'ebp8QKvnRqnFXiS+O/LQMke1ynVM0+2u4769QT6qoFk=' WHERE manager_id = 'pkejukjeon';
UPDATE tb_managerinfo SET manager_password = 'Wc8pYTAg1vVFC+gF07IOTXG07wfGWoxVEnEwm6x8Oz0=' WHERE manager_id = 'tradmin';
UPDATE tb_managerinfo SET manager_password = 'ABuOPhdk+vVRjL9pXmo7sdOvuUwf4GGIBiwae26fi+s=' WHERE manager_id = 'trgimpocc';
UPDATE tb_managerinfo SET manager_password = 'FzbZYPIDfUIVzsGz7rSAn4Sc0s53bGeFJPfWZW3k5Gc=' WHERE manager_id = 'echuncheoncc';
UPDATE tb_managerinfo SET manager_password = 'Cyj7/0HDT7y7DsGepH0e3SpxPduBpbHsFzcXiC3UNjo=' WHERE manager_id = 'eseongnamcc';
UPDATE tb_managerinfo SET manager_password = 'SdwgYeDSpkcx31aDvMjNntQKOuXZPoN8MNSjEqTv9BM=' WHERE manager_id = 'helpdesk';
UPDATE tb_managerinfo SET manager_password = 'CH75IeBHYlZVU+jJ1ZXvr2NGdNp8Zgj/1vknCzxvsbM=' WHERE manager_id = '095551';
UPDATE tb_managerinfo SET manager_password = 'jpGugJEXYQE9XRiZgn5B2k4EJ5KiGhhdM5cBSxAn5XY=' WHERE manager_id = 'shim657';
UPDATE tb_managerinfo SET manager_password = 'a1j16GBOYSGa/rWm28EsnleQoNPF10jJ96pnqnEHY88=' WHERE manager_id = 'idTest';
UPDATE tb_managerinfo SET manager_password = 'gBJdWgwGJiglIGmvUTcw8cDvjW4lfIfBxdI3xs5riTg=' WHERE manager_id = '129255';
UPDATE tb_managerinfo SET manager_password = 'PI8hPZAvr53NnzXlPBMIPC7QzchOeReTttrT2SyNOeg=' WHERE manager_id = 'tryeonsancc';
UPDATE tb_managerinfo SET manager_password = '4Q76egRHXfumD+e5z9QYyP1mDIon6j92bT3liGktf7c=' WHERE manager_id = 'boots001';
UPDATE tb_managerinfo SET manager_password = 'hZ5CaqXNUvZlNo4yH7eHXINyd9PIB0vxcTr0Zsw1Zsw=' WHERE manager_id = 'p909hz';
UPDATE tb_managerinfo SET manager_password = 'z3MCy9io7HrUxe9mLxtEOTqz12eAdG4LNmkCmr55QWY=' WHERE manager_id = 'pkenamyangju';
UPDATE tb_managerinfo SET manager_password = 'jXmwCip09rzuKMzUNYtTVKzIl6RiN7LBb3dDTalSAic=' WHERE manager_id = '115370';
UPDATE tb_managerinfo SET manager_password = 'rZJ5wM0VlnBXF67Jjd3JPVTwIzoPSD8VYEo3yDMhLRk=' WHERE manager_id = 'trgusungcc';
UPDATE tb_managerinfo SET manager_password = 'FIYykUL9OEH1D/gqZzcyob3z7pUDUBAX09QA8CAg9sw=' WHERE manager_id = 'epohangidcc';
UPDATE tb_managerinfo SET manager_password = 'oxS8LA1IU/hnexD97ko7caadvmVIDcFk+qKfLqfSBOs=' WHERE manager_id = 'wolgyeE_Daiz';
UPDATE tb_managerinfo SET manager_password = 'dj0optE1nyn/843bHwWT34jDSgEomJ8q4zUyBYMSKPs=' WHERE manager_id = 'trkintexcc';
UPDATE tb_managerinfo SET manager_password = 'rJaJ4ickJwheNbnT4+i+2IyzQ0gotDuG/AWWytTG4nA=' WHERE manager_id = 'admin';
UPDATE tb_managerinfo SET manager_password = 'E+7z2OqynK76zGLce9qhF/aw2gN+lZ4H07bW5jVaDvM=' WHERE manager_id = 'polizei';
UPDATE tb_managerinfo SET manager_password = 'C7Lv5UHa0jZG3LbGkmJxRMw06ron0sstbeH7xZASfOU=' WHERE manager_id = 'ewolgyecc';
UPDATE tb_managerinfo SET manager_password = '83FwRQCJNfLmtqqXzk2dmFt+G8yWBXL2MyvpGg/1ZSo=' WHERE manager_id = 'pkeguro';
UPDATE tb_managerinfo SET manager_password = 'wABU1BllC1kItGeTkC/t+FjOKQnr0ODpk0jWqMLXTTI=' WHERE manager_id = 'trsuwoncc';
UPDATE tb_managerinfo SET manager_password = 'fuWKa3p8jssQ590FhmSr//dm4pdTCmPQWn4hDARSmHA=' WHERE manager_id = 'cctest';
UPDATE tb_managerinfo SET manager_password = 'DuIzuGFt7PwO7UL8eKIiv0p9QcyCB1FQ+ua4+/z6c4Y=' WHERE manager_id = 'trkintexcom';
UPDATE tb_managerinfo SET manager_password = 'CRdsHPP7w2i4BoQCi+s5KpKLepzjcoH4f+tPWg5a4Ao=' WHERE manager_id = 'echeonansbfd';
UPDATE tb_managerinfo SET manager_password = 'UgTaBdyWUwfZVUQlV7spo6bdzPfwC/Q1L3m/udT2ckg=' WHERE manager_id = '114887';
UPDATE tb_managerinfo SET manager_password = 'muZiPpjLsrWFRmyYDHdcRwB3cJCgusLANJ3Dszmu5U8=' WHERE manager_id = '015536';
UPDATE tb_managerinfo SET manager_password = 'Tiiz5eE1UJFlAwqjpmmW/cZLRU3opZka5z0B9lO23g4=' WHERE manager_id = 'voicepop';
UPDATE tb_managerinfo SET manager_password = 'lb0aV/u3l2QkjePyj6BVSuoJn39p1QIVcpq0Mt13U6k=' WHERE manager_id = 'eyangjucc';
UPDATE tb_managerinfo SET manager_password = 'ON1jG65om/Vrff/Vx/uDI0IQId459mCxpMmXuc5Y/tM=' WHERE manager_id = 'egeomdancc';
UPDATE tb_managerinfo SET manager_password = 'y4h1fOEJfrZJCYu9hAiYDYoDLYrJ2YcRZpOP6zELxBI=' WHERE manager_id = 'eyangjaecc';
UPDATE tb_managerinfo SET manager_password = 'czOI38ZE38rUAb69pIbRLR9NyN2HU0do2EFxiynycrk=' WHERE manager_id = 'pierrot6405';
UPDATE tb_managerinfo SET manager_password = 'Hk9Y8Inrn98onbEMP8CeoMCw/tcBzRB0obxVbS9CXNc=' WHERE manager_id = 'eone';
UPDATE tb_managerinfo SET manager_password = 'RkN0qa4mudswxF1YaWzpu/L/p3tsPaKFECC7pvqOTH8=' WHERE manager_id = 'pksungsu';
UPDATE tb_managerinfo SET manager_password = 'tA3Ok3V1m8RR0jW0w5+3mQ3/kJteeZsDGOVysRvyp7w=' WHERE manager_id = 'atensys';
UPDATE tb_managerinfo SET manager_password = 'skd/ySJy1qIlUm61RjLjs1BG7Vkmz6hYqWFrO9w30ho=' WHERE manager_id = 'CC01';
UPDATE tb_managerinfo SET manager_password = 'VLIFGyl7tPckB+NX+biH9cGyO6bJCbEV0qCUcDudoXE=' WHERE manager_id = 'CC02';
UPDATE tb_managerinfo SET manager_password = 'Zrnp6Jt4yGFm7K96YBiKn2ivsYETtn9xSZ04Gmo9aWQ=' WHERE manager_id = 'SFMJCC';
UPDATE tb_managerinfo SET manager_password = 'TCYczNcI6Fm5yiXAO/2toiEItNcbfBiW9OGktNZucbc=' WHERE manager_id = 'ejukjeoncom';
UPDATE tb_managerinfo SET manager_password = 'Zcib1mddEnHjcz6YOCcAXr8MQY2fCL/03P+4whFQ3es=' WHERE manager_id = '201280';
UPDATE tb_managerinfo SET manager_password = 'P1nj7HY1qcMcntlovEQpiNP567OYPFfUZNARr9Sa2bQ=' WHERE manager_id = 'emokdongcc';
UPDATE tb_managerinfo SET manager_password = 'jKeLREghZY/4WhNEhEW1Z6/x07FezvEJi0BtQkznK8o=' WHERE manager_id = 'enamyangjucc';
UPDATE tb_managerinfo SET manager_password = 'LV2zIARpiVByekMH3VcVoiZOi0CC1ISPwH7fVjxOFEk=' WHERE manager_id = '061041';
UPDATE tb_managerinfo SET manager_password = 'nTXdPqRQ54cuxquHJr/Hv19wUPXxOUVO5AGwcg5bUCM=' WHERE manager_id = '024590';
UPDATE tb_managerinfo SET manager_password = 'yQX5ISvCleFiFWXMROFVSaGuyu99sIYrTzo8Y4Pc5xY=' WHERE manager_id = 'authorTest02';
UPDATE tb_managerinfo SET manager_password = 'Qz74RLVur2I3D8VcCG6Ym9TEszQnMl5e2Iaj1Iu09aY=' WHERE manager_id = 'authorTest01';
UPDATE tb_managerinfo SET manager_password = 'kGVqbjVa8i2gNiLdHO0HX6vNxK9T0Rogw0fwmGs7OPI=' WHERE manager_id = 'testid';
UPDATE tb_managerinfo SET manager_password = 'Z63UXt16SPMJ7TfMA258ZnmchTl0dO70y3x50/LNVj4=' WHERE manager_id = 'wolgyeE';
UPDATE tb_managerinfo SET manager_password = '1UNsb5ZvH5Sj2gZlbs0YJIQlKsy4YZiUTwzt/2szqvc=' WHERE manager_id = '110406';
UPDATE tb_managerinfo SET manager_password = 'bzhGQyIWorY4O3A5i7mxweaeGaoL+7+Gm1bKYD/yq4o=' WHERE manager_id = 'egyeongsancc';
UPDATE tb_managerinfo SET manager_password = 'obboAFhFMpE3E7ybsN5cy/W2b14gxF3nR2/cN7PceF0=' WHERE manager_id = 'trdongtancc';
UPDATE tb_managerinfo SET manager_password = 'ChJweSMy9vyAFxRH5AnLWDJJsdcFNejV7PSWPEF8Jjo=' WHERE manager_id = 'echeonancc';
UPDATE tb_managerinfo SET manager_password = 'vTFcwrbfMw/snEQ2pLi0bjzcjBqITtmjRlG3rHFg40U=' WHERE manager_id = 'magicheepo';

COMMIT;
